-- Insert real estate agencies and promoters
-- This migration inserts the provided list of agencies into the real_estate_agencies table

INSERT INTO real_estate_agencies (name, description, address, phone, email, website) VALUES
-- Promotores principales
('Aedas Homes', 'Promotora inmobiliaria líder en España especializada en vivienda residencial de calidad.', 'Madrid, España', '+34 900 000 000', 'info@aedashomes.com', 'https://www.aedashomes.com'),
('Metrovacesa', 'Una de las principales promotoras inmobiliarias de España con más de 100 años de experiencia.', 'Madrid, España', '+34 900 000 001', 'info@metrovacesa.es', 'https://www.metrovacesa.es'),
('Neinor Homes', 'Promotora inmobiliaria especializada en el desarrollo de proyectos residenciales de alta calidad.', 'Barcelona, España', '+34 900 000 002', 'info@neinor.com', 'https://www.neinor.com'),
('Vía Célere', 'Promotora inmobiliaria líder en el mercado español, especializada en vivienda nueva.', 'Madrid, España', '+34 900 000 003', 'info@viacelere.com', 'https://www.viacelere.com'),
('Habitat Inmobiliaria', 'Promotora inmobiliaria con amplia experiencia en el desarrollo de proyectos residenciales.', 'Barcelona, España', '+34 900 000 004', 'info@habitat.es', 'https://www.habitat.es'),
('Amenabar', 'Promotora inmobiliaria especializada en vivienda residencial y proyectos urbanísticos.', 'San Sebastián, España', '+34 900 000 005', 'info@amenabar.com', 'https://www.amenabar.com'),
('ASG Homes', 'Promotora inmobiliaria dedicada a la construcción de viviendas de calidad en toda España.', 'Valencia, España', '+34 900 000 006', 'info@asghomes.es', 'https://www.asghomes.es'),
('Kronos Homes', 'Promotora inmobiliaria especializada en proyectos residenciales de diseño y calidad.', 'Madrid, España', '+34 900 000 007', 'info@kronoshomes.com', 'https://www.kronoshomes.com'),
('Pryconsa', 'Promotora inmobiliaria con más de 50 años de experiencia en el sector.', 'Madrid, España', '+34 900 000 008', 'info@pryconsa.com', 'https://www.pryconsa.com'),
('Acciona Inmobiliaria', 'División inmobiliaria de Acciona, especializada en proyectos sostenibles y de alta calidad.', 'Madrid, España', '+34 900 000 009', 'info@acciona-inmobiliaria.com', 'https://www.acciona-inmobiliaria.com'),
('Culmia', 'Promotora inmobiliaria líder en el desarrollo de proyectos residenciales.', 'Madrid, España', '+34 900 000 010', 'info@culmia.com', 'https://www.culmia.com'),
('Insur Grupo', 'Grupo inmobiliario con amplia experiencia en promoción y gestión de proyectos residenciales.', 'Madrid, España', '+34 900 000 011', 'info@insurgrupo.com', 'https://www.insurgrupo.com'),
('TM Grupo Inmobiliario', 'Grupo inmobiliario especializado en promoción y gestión de proyectos residenciales y comerciales.', 'Madrid, España', '+34 900 000 012', 'info@tmgrupo.com', 'https://www.tmgrupo.com'),
('Gestilar', 'Promotora inmobiliaria especializada en proyectos residenciales de alta calidad.', 'Barcelona, España', '+34 900 000 013', 'info@gestilar.com', 'https://www.gestilar.com'),
('Caralca', 'Promotora inmobiliaria con experiencia en el desarrollo de proyectos residenciales.', 'Valencia, España', '+34 900 000 014', 'info@caralca.com', 'https://www.caralca.com'),
('Quadratia', 'Promotora inmobiliaria especializada en proyectos residenciales de diseño contemporáneo.', 'Madrid, España', '+34 900 000 015', 'info@quadratia.com', 'https://www.quadratia.com'),
('Procons Group', 'Grupo promotor especializado en proyectos residenciales y comerciales.', 'Barcelona, España', '+34 900 000 016', 'info@proconsgroup.com', 'https://www.proconsgroup.com'),
('Taylor Wimpey España', 'Filial española de Taylor Wimpey, una de las mayores promotoras del mundo.', 'Madrid, España', '+34 900 000 017', 'info@taylorwimpey.es', 'https://www.taylorwimpey.es'),
('Marbella Club Hills', 'Promotora especializada en proyectos residenciales de lujo en la Costa del Sol.', 'Marbella, España', '+34 900 000 018', 'info@marbellaclubhills.com', 'https://www.marbellaclubhills.com'),
('Dar Global', 'Promotora inmobiliaria internacional especializada en proyectos residenciales de alta gama.', 'Madrid, España', '+34 900 000 019', 'info@darglobal.com', 'https://www.darglobal.com'),
('Cordia', 'Promotora inmobiliaria especializada en proyectos residenciales y urbanísticos.', 'Barcelona, España', '+34 900 000 020', 'info@cordia.es', 'https://www.cordia.es'),
('Altaona Village', 'Promotora especializada en proyectos residenciales en la Costa Blanca.', 'Alicante, España', '+34 900 000 021', 'info@altaonavillage.com', 'https://www.altaonavillage.com'),
('Turis Promociones', 'Promotora inmobiliaria especializada en proyectos residenciales y turísticos.', 'Valencia, España', '+34 900 000 022', 'info@turispromociones.com', 'https://www.turispromociones.com'),
('Urmosa', 'Promotora inmobiliaria con experiencia en proyectos residenciales y comerciales.', 'Madrid, España', '+34 900 000 023', 'info@urmosa.com', 'https://www.urmosa.com'),
('Vapf', 'Promotora inmobiliaria especializada en proyectos residenciales de calidad.', 'Valencia, España', '+34 900 000 024', 'info@vapf.com', 'https://www.vapf.com'),
('Promopark', 'Promotora inmobiliaria especializada en proyectos residenciales y comerciales.', 'Madrid, España', '+34 900 000 025', 'info@promopark.es', 'https://www.promopark.es'),
('Sunplace', 'Promotora inmobiliaria especializada en proyectos residenciales en zonas costeras.', 'Alicante, España', '+34 900 000 026', 'info@sunplace.es', 'https://www.sunplace.es'),
('Victoria Playa', 'Promotora especializada en proyectos residenciales y turísticos en la Costa del Sol.', 'Málaga, España', '+34 900 000 027', 'info@victoriaplaya.com', 'https://www.victoriaplaya.com'),
('UrbesGolf Promociones', 'Promotora especializada en proyectos residenciales junto a campos de golf.', 'Marbella, España', '+34 900 000 028', 'info@urbesgolf.com', 'https://www.urbesgolf.com'),
('Suna Comercializadora', 'Comercializadora inmobiliaria especializada en la venta de viviendas nuevas.', 'Madrid, España', '+34 900 000 029', 'info@suna.es', 'https://www.suna.es'),
('Europa Promos', 'Promotora inmobiliaria especializada en proyectos residenciales en toda España.', 'Barcelona, España', '+34 900 000 030', 'info@europapromos.com', 'https://www.europapromos.com'),
('Ento (SNprojects)', 'Promotora inmobiliaria especializada en proyectos residenciales innovadores.', 'Madrid, España', '+34 900 000 031', 'info@ento.es', 'https://www.ento.es'),
('Convasa', 'Promotora inmobiliaria con experiencia en proyectos residenciales y comerciales.', 'Valencia, España', '+34 900 000 032', 'info@convasa.com', 'https://www.convasa.com'),
('Calida Homes', 'Promotora inmobiliaria especializada en viviendas de calidad y diseño.', 'Barcelona, España', '+34 900 000 033', 'info@calidahomes.com', 'https://www.calidahomes.com'),
('AJ Spain', 'Promotora inmobiliaria especializada en proyectos residenciales de alta calidad.', 'Madrid, España', '+34 900 000 034', 'info@ajspain.com', 'https://www.ajspain.com'),
('ATTC', 'Promotora inmobiliaria especializada en proyectos residenciales y comerciales.', 'Barcelona, España', '+34 900 000 035', 'info@attc.es', 'https://www.attc.es'),
('Zenia Paradise', 'Promotora especializada en proyectos residenciales de lujo en la Costa Blanca.', 'Alicante, España', '+34 900 000 036', 'info@zeniaparadise.com', 'https://www.zeniaparadise.com'),
('Zapata Projects', 'Promotora inmobiliaria especializada en proyectos residenciales de diseño.', 'Madrid, España', '+34 900 000 037', 'info@zapataprojects.com', 'https://www.zapataprojects.com'),
('Viviendízate', 'Promotora inmobiliaria especializada en proyectos residenciales accesibles.', 'Valencia, España', '+34 900 000 038', 'info@viviendizate.com', 'https://www.viviendizate.com'),
('Vistabella Golf', 'Promotora especializada en proyectos residenciales junto a campos de golf.', 'Alicante, España', '+34 900 000 039', 'info@vistabellagolf.com', 'https://www.vistabellagolf.com'),
('Triton', 'Promotora inmobiliaria especializada en proyectos residenciales y comerciales.', 'Madrid, España', '+34 900 000 040', 'info@triton.es', 'https://www.triton.es'),
('Torregolf Homes', 'Promotora especializada en proyectos residenciales de lujo junto a campos de golf.', 'Marbella, España', '+34 900 000 041', 'info@torregolfhomes.com', 'https://www.torregolfhomes.com'),
('New Homes Global', 'Promotora inmobiliaria internacional especializada en proyectos residenciales.', 'Madrid, España', '+34 900 000 042', 'info@newhomesglobal.com', 'https://www.newhomesglobal.com'),
-- Gestión vacacional
('Rigech', 'Empresa especializada en gestión vacacional y alquiler de propiedades turísticas.', 'Marbella, España', '+34 900 000 043', 'info@rigech.com', 'https://www.rigech.com'),
('GuestReady', 'Plataforma de gestión vacacional para propiedades turísticas.', 'Barcelona, España', '+34 900 000 044', 'info@guestready.com', 'https://www.guestready.com'),
('Weguest', 'Empresa especializada en gestión vacacional y servicios para propiedades turísticas.', 'Madrid, España', '+34 900 000 045', 'info@weguest.com', 'https://www.weguest.com'),
('TheKey Host', 'Servicios de gestión vacacional y alquiler de propiedades turísticas.', 'Málaga, España', '+34 900 000 046', 'info@thekeyhost.com', 'https://www.thekeyhost.com'),
('The Charming Concept', 'Empresa de gestión vacacional especializada en propiedades de lujo.', 'Marbella, España', '+34 900 000 047', 'info@thecharmingconcept.com', 'https://www.thecharmingconcept.com'),
-- Inmobiliarias
('REMAX España', 'Red inmobiliaria internacional líder en el mercado español.', 'Madrid, España', '+34 900 000 048', 'info@remax.es', 'https://www.remax.es'),
('Lucas Fox', 'Inmobiliaria especializada en propiedades de lujo en la Costa del Sol y Barcelona.', 'Marbella, España', '+34 900 000 049', 'info@lucasfox.com', 'https://www.lucasfox.com'),
('Engel & Völkers', 'Inmobiliaria internacional especializada en propiedades premium y de lujo.', 'Madrid, España', '+34 900 000 050', 'info@engelvoelkers.es', 'https://www.engelvoelkers.es'),
('Century 21', 'Red inmobiliaria internacional con presencia en toda España.', 'Madrid, España', '+34 900 000 051', 'info@century21.es', 'https://www.century21.es'),
('Tecnocasa', 'Red inmobiliaria especializada en la comercialización de propiedades.', 'Barcelona, España', '+34 900 000 052', 'info@tecnocasa.es', 'https://www.tecnocasa.es'),
('Donpiso', 'Red inmobiliaria con amplia presencia en toda España.', 'Madrid, España', '+34 900 000 053', 'info@donpiso.com', 'https://www.donpiso.com'),
('Activum Real Estate Consulting', 'Consultoría inmobiliaria especializada en inversiones y desarrollo.', 'Madrid, España', '+34 900 000 054', 'info@activum.com', 'https://www.activum.com'),
('Nozar', 'Inmobiliaria especializada en propiedades residenciales y comerciales.', 'Barcelona, España', '+34 900 000 055', 'info@nozar.com', 'https://www.nozar.com'),
('Amenavar', 'Inmobiliaria especializada en propiedades residenciales y comerciales.', 'San Sebastián, España', '+34 900 000 056', 'info@amenavar.com', 'https://www.amenavar.com'),
('Carteia Homes', 'Inmobiliaria especializada en propiedades residenciales de calidad.', 'Madrid, España', '+34 900 000 057', 'info@carteiahomes.com', 'https://www.carteiahomes.com'),
('SunPlace', 'Inmobiliaria especializada en propiedades en zonas costeras.', 'Alicante, España', '+34 900 000 058', 'info@sunplace.es', 'https://www.sunplace.es'),
('AJ Spain Properties', 'Inmobiliaria especializada en propiedades residenciales de alta calidad.', 'Madrid, España', '+34 900 000 059', 'info@ajspainproperties.com', 'https://www.ajspainproperties.com'),
('Vistabella Golf Homes', 'Inmobiliaria especializada en propiedades junto a campos de golf.', 'Alicante, España', '+34 900 000 060', 'info@vistabellagolfhomes.com', 'https://www.vistabellagolfhomes.com'),
('Grupo Insur', 'Grupo inmobiliario con amplia experiencia en promoción y gestión de proyectos.', 'Madrid, España', '+34 900 000 061', 'info@grupoinsur.com', 'https://www.grupoinsur.com')
ON CONFLICT (name) DO NOTHING;

