// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpneiupvzsqzyrurcgmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwbmVpdXB2enNxenlydXJjZ21vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1Nzk3MjUsImV4cCI6MjA2MTE1NTcyNX0.MwM55HG_n-j6YpDBoe-NqFsHhqp6o5IgeYniM6fn4nM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);